variable "aws_region" {}
variable "aws_profile" {}
variable "key_name" {}
variable "public_key_path" {}
variable "private_key_path" {}
variable "dev_instance_type" {}
variable "dev_ami" {}
variable "security_group_id" {}
variable "localip" {}
